<script setup lang="ts">
import { Gift } from "lucide-vue-next";

/**
 * Full-width scrolling promo strip for gift certificates — homepage only,
 * placed right after the courses section (see pages/index.vue), same spot
 * conceptually as a "free shipping" ticker.
 *
 * The whole strip is one link (single accessible name via aria-label); the
 * scrolling text itself is aria-hidden since it's the same sentence
 * repeated many times purely for the continuous-scroll effect, which would
 * otherwise be read out loud once per repeat.
 *
 * Seamless loop: REPEAT_COUNT copies of one unit (icon + text) sit in a
 * `w-max` row, scrolled from translateX(0) to translateX(-50%). Because
 * every copy is identical, sliding by exactly half the track's width lands
 * on a pixel-identical frame to the start — this only self-aligns when
 * REPEAT_COUNT is even, so it must stay even if ever changed.
 *
 * The scroll runs on the Web Animations API rather than a CSS `animation`,
 * specifically so hover can *slow it down* without a visual jump: a CSS
 * `animation-duration` change recomputes position as (elapsed / duration)
 * of the keyframe distance, so swapping duration mid-flight snaps the
 * track to a different point instantly. `playbackRate` instead changes how
 * fast the same running timeline advances from wherever it currently is —
 * same position, just a different speed from that moment on.
 */
const REPEAT_COUNT = 8;
const BASE_DURATION_MS = 24_000;
const HOVER_PLAYBACK_RATE = 0.4;

const { text } = await usePageContent();
const message = computed(() =>
  text("gift_certificate_marquee_text", "Подарочные сертификаты — порадуйте близких цветами"),
);

const trackEl = ref<HTMLElement | null>(null);
let scrollAnimation: Animation | null = null;

onMounted(() => {
  if (!trackEl.value) return;
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  scrollAnimation = trackEl.value.animate(
    [{ transform: "translateX(0)" }, { transform: "translateX(-50%)" }],
    { duration: BASE_DURATION_MS, iterations: Infinity, easing: "linear" },
  );
});

onUnmounted(() => {
  scrollAnimation?.cancel();
});

function onHoverStart() {
  if (scrollAnimation) scrollAnimation.playbackRate = HOVER_PLAYBACK_RATE;
}
function onHoverEnd() {
  if (scrollAnimation) scrollAnimation.playbackRate = 1;
}
</script>

<template>
  <NuxtLink
    to="/sertifikaty"
    :aria-label="message"
    class="group relative block w-full cursor-pointer overflow-hidden bg-primary py-12 motion-reduce:hover:animate-none hover:animate-[gift-marquee-shake_0.6s_ease-in-out_infinite]"
    @mouseenter="onHoverStart"
    @mouseleave="onHoverEnd"
  >
    <div ref="trackEl" aria-hidden="true" class="flex w-max items-center gap-48 whitespace-nowrap">
      <span v-for="n in REPEAT_COUNT" :key="n" class="flex shrink-0 items-center gap-12">
        <Gift class="size-24 shrink-0 text-white" aria-hidden="true" />
        <span class="font-display text-h4 text-white">{{ message }}</span>
      </span>
    </div>
  </NuxtLink>
</template>

<!-- Not scoped, deliberately (see the shake keyframes below): Vue renames
keyframes declared in a scoped block (appends the component's data-v-xxx
suffix), but this one is referenced via a Tailwind arbitrary-value class in
the template (`hover:animate-[gift-marquee-shake_...]`), generated by
Tailwind unaware of that renaming — the two names would stop matching and
the animation would silently never play. -->
<style>
@keyframes gift-marquee-shake {
  0%,
  100% {
    transform: translateY(0);
  }
  25% {
    transform: translateY(-3px);
  }
  75% {
    transform: translateY(3px);
  }
}
</style>
